// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwjjdouliodjkyriggxl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3ampkb3VsaW9kamt5cmlnZ3hsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzgwNDI0OTIsImV4cCI6MjA5MzYxODQ5Mn0.KosZt-wapQJRKl7HpCSoEau7AS-8N92OOSIgr-wBnBI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});